### ISSUE TITLE
Use MacGap

### ISSUE THREAD

**Issue by subtleGradient** [subtleGradient/Appify-UI#8]
Cf. #1

**Comment by Hum4n01d** [comment]
Electron is (probably) better 😄

**Comment by subtleGradient** [comment]
Electron contains all of node and chromium combined. This contains almost
nothing. The point of this project is minimalism. Better is relative 😬

**Comment by Hum4n01d** [comment]
Ok, idk but Electron is great and much newer

**Comment by subtleGradient** [comment]
Very true. Electron is also used for lots of real and important projects.
Appify-UI is a toy. I like like them both

**Comment by subtleGradient** [comment]
https://github.com/MacGapProject/MacGap2/issues/65#issuecomment-163096669
Seems like the best option is to continue working on the Appify UI 23 code I started
